CREATE DATABASE `cif_test` /*!40100 DEFAULT CHARACTER SET utf8 */;
use cif_test;
create table Candidate ( CID int(5) primary key, 
EmployeeName varchar(30) not null, 
EmployeeId varchar(7) default null);



CREATE TABLE PERSONAL_DETAILS( CID INT(5) PRIMARY KEY,
TITLE VARCHAR(4) NOT NULL, 
FIRSTNAME VARCHAR(25) NOT NULL, 
MIDDLENAME VARCHAR(25), 
LASTNAME VARCHAR(25),
GENDER CHAR,
DOB DATE NOT NULL,
PLACE_OF_BIRTH VARCHAR(30) NOT NULL,
MOB_NUMBER INTEGER(13) NOT NULL,
PERSONAL_EMAAILID VARCHAR(30),
NATIONALITY VARCHAR(15) NOT NULL,
PASSPORT_NO VARCHAR(15) NOT NULL,
PAN_NO VARCHAR(15) NOT NULL,
NASSCOM_NSR_ITPIN VARCHAR(50) DEFAULT NULL,
FATHER_NAME VARCHAR(25) NOT NULL,
FATHER_DOB DATE NOT NULL,
MOTHER_NAME VARCHAR(25) NOT NULL,
MOTHER_DOB DATE NOT NULL,
SPOUSE_NAME VARCHAR(25) NOT NULL,
SPOUSE_DOB DATE NOT NULL,
CHILD1_NAME VARCHAR(25) NOT NULL,
CHILD1_DOB DATE NOT NULL,
CHILD2_NAME VARCHAR(25) NOT NULL,
CHILD2_DOB DATE NOT NULL,
CHILD3_NAME VARCHAR(25) NOT NULL,
CHILD3_DOB DATE NOT NULL,
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));


CREATE TABLE ADDRESS_DETAILS(
CID INT(5) NOT NULL,
ADDRESS_TYPE CHAR NOT NULL,
ADDRESS VARCHAR(300) NOT NULL,
CITY VARCHAR(20),
STATE VARCHAR(20),
LANDMARK VARCHAR(30),
STAY_FROM DATE,
STAY_TILDATE DATE, 
PINCODE INT(6) NOT NULL,
TELEPHONE INT(15),
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMERGENCY_DETAILS (
CID INT(5) NOT NULL, 
BLOODGROUP VARCHAR(6), 
ALLERGICTO VARCHAR(100), 
BLOODPRESSURE VARCHAR(20), 
EYESIGHTLEFT VARCHAR(20), 
EYESIGHTRIGHT VARCHAR(20), 
MAJORILLNESS  VARCHAR(100), 
EMERGENCYTCONTACTNAME VARCHAR(100) NOT NULL, 
EMERGENCYTCONTACTADDRESSPHONE VARCHAR(100) NOT NULL, 
EMERGENCYTCONTACTPHONE INT(20) NOT NULL,
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));


CREATE TABLE EMPLOYMENT_DETAILS (
CID INT(5) NOT NULL, 
EMPLOYMENTNO VARCHAR(6) NOT NULL, 
ORGANIZATIONNAME VARCHAR(100) NOT NULL, 
BRANCHADDRESS VARCHAR(20), 
EMPLOYEEID INT(20) NOT NULL, 
EMPLOYMENT_PERIOD_START DATE,
EMPLOYMENT_PERIOD_END DATE, 
LASTDESIGNATION  VARCHAR(100) NOT NULL, 
LASTDRAWNSALARY VARCHAR(100), 
REPORTEENAME VARCHAR(100),
REPORTEEDESIG VARCHAR(100),
REPORTEECONTACTNO INT(20),
LEAVINGREASON VARCHAR(100), 
SEPARATIONMODE VARCHAR(100) NOT NULL, 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMPLOYMENT_BREAK (
CID INT(5) NOT NULL, 
EMPLOYMENTBREAKTYPE CHAR NOT NULL, 
DURATIONFROM DATE NOT NULL,
DURATIONTO DATE NOT NULL, 
REASON  VARCHAR(200) NOT NULL, 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMPLOYMENT_REFERENCE (
CID INT(5) NOT NULL, 
REF_NO INT(1) NOT NULL, 
REF_NAME VARCHAR(20) NOT NULL, 
REF_DESIGNATION VARCHAR(30), 
REF_ORG VARCHAR(100),
REF_CONTACT_NO INT(20), 
ACQUAINTANCE_PERIOD_START DATE,
ACQUAINTANCE_PERIOD_END DATE, 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

insert into candidate value (1,'aaa',1);
delete from candidate where 1=1;
select * from candidate;


