CREATE DATABASE `cif_test` /*!40100 DEFAULT CHARACTER SET utf8 */;
use cif_test_db;
create table Candidate( CID int(5) primary key AUTO_INCREMENT, 
EmployeeName varchar(30) not null, 
EmployeeId varchar(7) default null);

CREATE TABLE PERSONAL_DETAILS( CID INT(5) PRIMARY KEY,
TITLE VARCHAR(4) NOT NULL, 
FIRSTNAME VARCHAR(25) NOT NULL, 
MIDDLENAME VARCHAR(25), 
LASTNAME VARCHAR(25),
GENDER CHAR,
DOB DATE NOT NULL,
PLACE_OF_BIRTH VARCHAR(30) NOT NULL,
MOB_NUMBER BIGINT NOT NULL,
ALT_MOB_NUM BIGINT,
PERSONAL_EMAILID VARCHAR(30),
NATIONALITY VARCHAR(15) NOT NULL,
PASSPORT_NO VARCHAR(15) NOT NULL,
PAN_NO VARCHAR(15) NOT NULL,
NASSCOM_NSR_ITPIN VARCHAR(50) DEFAULT NULL,
FATHER_NAME VARCHAR(25) NOT NULL,
FATHER_DOB DATE NOT NULL,
MOTHER_NAME VARCHAR(25) NOT NULL,
MOTHER_DOB DATE NOT NULL,
SPOUSE_NAME VARCHAR(25) NOT NULL,
SPOUSE_DOB DATE NOT NULL,
CHILD_DETAILS varchar(500),
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE ADDRESS_DETAILS(
CID INT(5) NOT NULL,
ADDRESS_TYPE CHAR NOT NULL,
ADDRESS VARCHAR(1000) NOT NULL,
CITY VARCHAR(20),
STATE VARCHAR(20),
LANDMARK VARCHAR(30),
STAY_FROM DATE,
STAY_TILDATE DATE, 
PINCODE INT(6) NOT NULL,
TELEPHONE BIGINT,
DURATION varchar(100),
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMERGENCY_DETAILS (

CID INT(5) NOT NULL, 
BLOODGROUP VARCHAR(6), 
ALLERGICTO VARCHAR(100), 
BLOODPRESSURE VARCHAR(20), 
EYESIGHTLEFT VARCHAR(20), 
EYESIGHTRIGHT VARCHAR(20), 
MAJORILLNESS  VARCHAR(100), 
EMER_CONT_NAME VARCHAR(100) NOT NULL, 
EMER_CONT_ADDR_PH VARCHAR(100) NOT NULL, 
EMER_CONT_PH BIGINT NOT NULL,
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE REFERENCE_DETAILS (
CID INT(5) NOT NULL, 
REF_NAME varchar(30), 
DESIGNATION VARCHAR(100), 
ORGANIZATION VARCHAR(100), 
CONTACT BIGINT, 
EMAIL VARCHAR(100), 
ACQUAINTANCE_PERIOD  VARCHAR(100), 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EDUCATION_DETAILS (
CID INT(5) NOT NULL, 
CLASSLEVEL VARCHAR(18) NOT NULL, 
SCHOOL_NAME VARCHAR(100) NOT NULL, 
BOARD VARCHAR(30) NOT NULL, 
DURATION varchar(45) NOT NULL, 
PASSING_YEAR YEAR NOT NULL,
PERCENTAGE INT(100) NOT NULL,
eduGapReason VARCHAR(250),
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMPLOYMENT_DETAILS (
CID INT(5) NOT NULL, 
EMPLOYMENTNO VARCHAR(10), 
ORGANIZATIONNAME VARCHAR(100), 
BRANCHADDRESS VARCHAR(20), 
EMPLOYEEID varchar(20) NOT NULL, 
EMPLOYMENT_PERIOD_START DATE,
EMPLOYMENT_PERIOD_END DATE, 
LASTDESIGNATION  VARCHAR(100) NOT NULL, 
LASTDRAWNSALARY VARCHAR(100), 
REPORTEENAME VARCHAR(100),
REPORTEEDESIG VARCHAR(100),
REPORTEECONTACTNO BIGINT,
LEAVINGREASON VARCHAR(100), 
SEPARATIONMODE VARCHAR(100) NOT NULL, 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));

CREATE TABLE EMPLOYMENT_BREAK (
CID INT(5) NOT NULL, 
EMPLOYMENT_BREAK_FROM DATE,
EMPLOYMENT_BREAK_TO DATE, 
EMPLOYMENT_BREAK_REASON  VARCHAR(200), 
STUDY_EMPLOYMENT_BREAK_FROM DATE,
STUDY_EMPLOYMENT_BREAK_TO DATE, 
STUDY_EMPLOYMENT_BREAK_REASON  VARCHAR(200), 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));


CREATE TABLE EMPLOYMENT_REFERENCE (
CID INT(5) NOT NULL, 
REF_NO INT(1) NOT NULL, 
REF_NAME VARCHAR(20) NOT NULL, 
REF_DESIGNATION VARCHAR(30), 
REF_ORG VARCHAR(100),
REF_CONTACT_NO INT(20), 
ACQUAINTANCE_PERIOD_START DATE,
ACQUAINTANCE_PERIOD_END DATE, 
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));




CREATE TABLE ADDITIONAL_INFORMATION(
CID int(5) NOT NULL,
PHYSICAL_DISABILITIES VARCHAR(500),
COURT_PROCEEDING_SUMMARY VARCHAR(1000),
PROWARENESS_PREV_INTVW_DATE DATE,
PROWARENESS_PREV_INTVW_POSITION VARCHAR(150),
PROWARENESS_PREV_INTVW_OUTCOME VARCHAR(150),
HOBBIES VARCHAR(900),
INTERESTS VARCHAR(900),
GOAL_OR_AIM VARCHAR(1000),
PRINCIPALS_IDEALS_LIFEGUIDE VARCHAR(200),
STRENGTH VARCHAR(500),
WEAKNESS  VARCHAR(500),
TRAVEL_INDIA VARCHAR(600),
TRAVEL_ABROAD VARCHAR(600),
RESTRICTIONS_ON_TRAVEL VARCHAR(600),
PROWARE_EMP_RELATION_NAME VARCHAR(50),
PUBLICATIONS VARCHAR(500),
SPECIALIZED_TRAININGS VARCHAR(500),
INTEREST_ON_SPECIFIC_TRAININGS VARCHAR(500),
OTHER_INFORMATION VARCHAR(1000),
FOREIGN KEY (CID) REFERENCES CANDIDATE(CID));
